DROP TABLE IF EXISTS submissions;
DROP TABLE IF EXISTS user_progress;
DROP TABLE IF EXISTS questions;
DROP TABLE IF EXISTS levels;
DROP TABLE IF EXISTS users;

SET FOREIGN_KEY_CHECKS = 1;

-- Table Structures
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    is_admin TINYINT(1) DEFAULT 0,
    total_points INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE levels (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    required_points INT DEFAULT 0,
    display_order INT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE questions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    level_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    code_snippet TEXT,
    expected_answer TEXT NOT NULL,
    expected_output TEXT,
    type ENUM('fix-code', 'write-code', 'sql-query') DEFAULT 'fix-code',
    points INT DEFAULT 100,
    language VARCHAR(50) DEFAULT 'java',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (level_id) REFERENCES levels(id) ON DELETE CASCADE
);

CREATE TABLE user_progress (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    question_id INT NOT NULL,
    completed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE,
    UNIQUE KEY unique_user_question (user_id, question_id)
);

CREATE TABLE submissions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    question_id INT NOT NULL,
    code TEXT NOT NULL,
    is_correct TINYINT(1) DEFAULT 0,
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE
);

-- DATA INSERTION

-- Default Admin
INSERT INTO users (username, email, password, is_admin, total_points) VALUES 
('admin', 'admin@example.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 0);

-- 8 Levels for Grade 12 (Added 3 Hard Levels)
INSERT INTO levels (id, name, required_points, display_order) VALUES 
(1, 'the coder wanna be', 0, 1),
(2, 'vibe coder', 300, 2),
(3, 'wow pro', 700, 3),
(4, 'logic analyzer', 900, 4),
(5, 'mastery', 1300, 5),
(6, 'cyber warrior', 2500, 6),
(7, 'system architect', 4500, 7),
(8, 'coding deity', 7000, 8);

-- LEVEL 1: DATA TYPES
INSERT INTO questions (level_id, title, description, code_snippet, expected_answer, expected_output, type, points, language) VALUES 
(1, 'Int Overflow', 'Declare an integer x with max value and print it. Fix the code.', 'public class Main {\n  public static void main(String[] args) {\n    int x = 0;\n    System.out.println(x);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int x = Integer.MAX_VALUE;\n    System.out.println(x);\n  }\n}', '2147483647', 'fix-code', 180, 'java'),
(1, 'Long Literal', 'Assign 10 billion to a long variable L. Fix the literal syntax.', 'public class Main {\n  public static void main(String[] args) {\n    long L = 10000000000;\n    System.out.println(L);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    long L = 10000000000L;\n    System.out.println(L);\n  }\n}', '10000000000', 'fix-code', 215, 'java'),
(1, 'Float Precision', 'Declare a float f with 3.1415. Fix the suffix.', 'public class Main {\n  public static void main(String[] args) {\n    float f = 3.1415;\n    System.out.println(f);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    float f = 3.1415f;\n    System.out.println(f);\n  }\n}', '3.1415', 'fix-code', 205, 'java'),
(1, 'Char Unicode', 'Print the char literal for Unicode value 65. Fix the cast.', 'public class Main {\n  public static void main(String[] args) {\n    System.out.println(65);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    System.out.println((char)65);\n  }\n}', 'A', 'fix-code', 190, 'java'),
(1, 'Double Scientific', 'Declare 1.5e3 as a double. Fix the variable name.', 'public class Main {\n  public static void main(String[] args) {\n    double val = 1.5e3;\n    System.out.println(d);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    double d = 1.5e3;\n    System.out.println(d);\n  }\n}', '1500.0', 'fix-code', 230, 'java'),
(1, 'Boolean Logic', 'Assign result of 5 > 3 to a boolean b.', 'public class Main {\n  public static void main(String[] args) {\n    boolean b = 5 < 3;\n    System.out.println(b);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    boolean b = 5 > 3;\n    System.out.println(b);\n  }\n}', 'true', 'fix-code', 175, 'java'),
(1, 'Byte Limit', 'What is the max value of byte?', 'public class Main {\n  public static void main(String[] args) {\n    System.out.println(Byte.MIN_VALUE);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    System.out.println(Byte.MAX_VALUE);\n  }\n}', '127', 'fix-code', 160, 'java'),
(1, 'Short Range', 'Declare a short variable s = 30000. Fix the type.', 'public class Main {\n  public static void main(String[] args) {\n    byte s = 30000;\n    System.out.println(s);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    short s = 30000;\n    System.out.println(s);\n  }\n}', '30000', 'fix-code', 195, 'java'),
(1, 'String Object', 'Create a String using "new" keyword. Fix the quotes.', 'public class Main {\n  public static void main(String[] args) {\n    String s = new String(Java);\n    System.out.println(s);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    String s = new String("Java");\n    System.out.println(s);\n  }\n}', 'Java', 'fix-code', 210, 'java'),
(1, 'Final Value', 'Declare a final int PI_INT = 3. Fix the keyword.', 'public class Main {\n  public static void main(String[] args) {\n    static int PI_INT = 3;\n    System.out.println(PI_INT);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    final int PI_INT = 3;\n    System.out.println(PI_INT);\n  }\n}', '3', 'fix-code', 185, 'java'),
(1, 'Default Int', 'What is the default value of an uninitialized int field? Fix the code to print 0.', 'public class Main {\n  static int x = 100;\n  public static void main(String[] args) {\n    System.out.println(x);\n  }\n}', 'public class Main {\n  static int x;\n  public static void main(String[] args) {\n    System.out.println(x);\n  }\n}', '0', 'fix-code', 220, 'java'),
(1, 'Type Casting Int to Float', 'Explicitly cast int 5 to float.', 'public class Main {\n  public static void main(String[] args) {\n    int i = 5;\n    System.out.println(i);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int i = 5;\n    System.out.println((float)i);\n  }\n}', '5.0', 'fix-code', 200, 'java'),
(1, 'Widening Casting', 'Assign byte to int automatically.', 'public class Main {\n  public static void main(String[] args) {\n    byte b = 10;\n    float x = b;\n    System.out.println(x);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    byte b = 10;\n    int x = b;\n    System.out.println(x);\n  }\n}', '10', 'fix-code', 190, 'java'),
(1, 'Precision Loss', 'Cast double 9.99 to int.', 'public class Main {\n  public static void main(String[] args) {\n    double d = 9.99;\n    System.out.println(d);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    double d = 9.99;\n    System.out.println((int)d);\n  }\n}', '9', 'fix-code', 240, 'java'),
(1, 'Var Keyword', 'Use "var" keyword for string "Code". Fix the type name.', 'public class Main {\n  public static void main(String[] args) {\n    String s = "Code";\n    System.out.println(s);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    var s = "Code";\n    System.out.println(s);\n  }\n}', 'Code', 'fix-code', 275, 'java');

-- LEVEL 2: Mixed (No Scanner version)
INSERT INTO questions (level_id, title, description, code_snippet, expected_answer, expected_output, type, points, language) VALUES 
(2, 'Underscores in Literals', 'Declare 1,000,000 using underscores. Fix the position.', 'public class Main {\n  public static void main(String[] args) {\n    int n = _1000000;\n    System.out.println(n);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int n = 1_000_000;\n    System.out.println(n);\n  }\n}', '1000000', 'fix-code', 280, 'java'),
(2, 'Binary Literal', 'Declare decimal 5 in binary literal. Fix the prefix.', 'public class Main {\n  public static void main(String[] args) {\n    int n = 101;\n    System.out.println(n);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int n = 0b101;\n    System.out.println(n);\n  }\n}', '5', 'fix-code', 310, 'java'),
(2, 'Hex Literal', 'Declare decimal 15 in hex. Fix the value.', 'public class Main {\n  public static void main(String[] args) {\n    int n = 0xE;\n    System.out.println(n);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int n = 0xF;\n    System.out.println(n);\n  }\n}', '15', 'fix-code', 295, 'java'),
(2, 'Char Escape', 'Print a tab space using escape.', 'public class Main {\n  public static void main(String[] args) {\n    System.out.println("A" + "B");\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    System.out.println("A\\tB");\n  }\n}', 'A	B', 'fix-code', 320, 'java'),
(2, 'Null String', 'Declare a null string "s". Fix the assignment.', 'public class Main {\n  public static void main(String[] args) {\n    String s = "";\n    System.out.println(s);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    String s = null;\n    System.out.println(s);\n  }\n}', 'null', 'fix-code', 260, 'java'),
(2, 'Arithmetic Order', 'Calculate 5 + 2 * 3. Fix the expected output logic.', 'public class Main {\n  public static void main(String[] args) {\n    int n = (5 + 2) * 3;\n    System.out.println(n);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int n = 5 + 2 * 3;\n    System.out.println(n);\n  }\n}', '11', 'fix-code', 340, 'java'),
(2, 'Post-increment', 'Print the value after incrementing i.', 'public class Main {\n  public static void main(String[] args) {\n    int i = 5;\n    System.out.println(i);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int i = 5;\n    System.out.println(i++);\n  }\n}', '5', 'fix-code', 380, 'java'),
(2, 'Modulus Math', 'Find remainder of 10 divided by 3.', 'public class Main {\n  public static void main(String[] args) {\n    int r = 10 / 3;\n    System.out.println(r);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int r = 10 % 3;\n    System.out.println(r);\n  }\n}', '1', 'fix-code', 355, 'java'),
(2, 'Absolute Value', 'Use Math.abs to print absolute of -10.', 'public class Main {\n  public static void main(String[] args) {\n    int x = -10;\n    System.out.println(x);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int x = -10;\n    System.out.println(Math.abs(x));\n  }\n}', '10', 'fix-code', 410, 'java'),
(2, 'Power Function', 'Calculate 2 to the power of 3 using Math.pow.', 'public class Main {\n  public static void main(String[] args) {\n    double p = 2 * 3;\n    System.out.println(p);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    double p = Math.pow(2, 3);\n    System.out.println(p);\n  }\n}', '8.0', 'fix-code', 365, 'java'),
(2, 'Logical XOR', 'Use the XOR operator for logic.', 'public class Main {\n  public static void main(String[] args) {\n    boolean b = true && false;\n    System.out.println(b);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    boolean b = true ^ false;\n    System.out.println(b);\n  }\n}', 'true', 'fix-code', 290, 'java'),
(2, 'String Length', 'Find length of "Java".', 'public class Main {\n  public static void main(String[] args) {\n    String s = "Java";\n    System.out.println(s.length());\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    String s = "Java";\n    System.out.println(s.length());\n  }\n}', '4', 'fix-code', 450, 'java'),
(2, 'String CharAt', 'Get first character of "Hello".', 'public class Main {\n  public static void main(String[] args) {\n    String s = "Hello";\n    System.out.println(s.charAt(1));\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    String s = "Hello";\n    System.out.println(s.charAt(0));\n  }\n}', 'H', 'fix-code', 420, 'java'),
(2, 'String ToUpperCase', 'Convert "code" to uppercase.', 'public class Main {\n  public static void main(String[] args) {\n    String s = "code";\n    System.out.println(s);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    String s = "code";\n    System.out.println(s.toUpperCase());\n  }\n}', 'CODE', 'fix-code', 335, 'java'),
(2, 'Math Sqrt', 'Calculate square root of 16.', 'public class Main {\n  public static void main(String[] args) {\n    double s = 16;\n    System.out.println(s);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    double s = Math.sqrt(16);\n    System.out.println(s);\n  }\n}', '4.0', 'fix-code', 485, 'java');

-- LEVEL 3: Selection
INSERT INTO questions (level_id, title, description, code_snippet, expected_answer, expected_output, type, points, language) VALUES 
(3, 'Simple If', 'Print "Yes" if 10 > 5. Fix logic.', 'public class Main {\n  public static void main(String[] args) {\n    if(10 < 5) System.out.println("Yes");\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    if(10 > 5) System.out.println("Yes");\n  }\n}', 'Yes', 'fix-code', 410, 'java'),
(3, 'If-Else Block', 'Print "Pass" if score >= 75 else "Fail". Fix syntax.', 'public class Main {\n  public static void main(String[] args) {\n    int score = 80;\n    if(score >= 75) System.out.println("Pass")\n    else System.out.println("Fail");\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int score = 80;\n    if(score >= 75) System.out.println("Pass");\n    else System.out.println("Fail");\n  }\n}', 'Pass', 'fix-code', 445, 'java'),
(3, 'Else-If Ladder', 'Print "A" if score >= 90, "B" if >= 80. Fix logic.', 'public class Main {\n  public static void main(String[] args) {\n    int score = 85;\n    if(score >= 90) System.out.println("A");\n    if(score >= 80) System.out.println("B");\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int score = 85;\n    if(score >= 90) System.out.println("A");\n    else if(score >= 80) System.out.println("B");\n  }\n}', 'B', 'fix-code', 490, 'java'),
(3, 'Nested If', 'Check if n is positive AND even. Fix brackets.', 'public class Main {\n  public static void main(String[] args) {\n    int n = 4;\n    if(n > 0) \n      if(n % 2 == 0) System.out.println("Positive Even");\n    \n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int n = 4;\n    if(n > 0) {\n      if(n % 2 == 0) System.out.println("Positive Even");\n    }\n  }\n}', 'Positive Even', 'fix-code', 530, 'java'),
(3, 'Logical OR If', 'If x is 1 OR 2, print "Valid". Fix operator.', 'public class Main {\n  public static void main(String[] args) {\n    int x = 2;\n    if(x == 1 && x == 2) System.out.println("Valid");\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int x = 2;\n    if(x == 1 || x == 2) System.out.println("Valid");\n  }\n}', 'Valid', 'fix-code', 475, 'java'),
(3, 'Not Operator', 'If NOT true, print "Wait". Fix logic.', 'public class Main {\n  public static void main(String[] args) {\n    boolean open = false;\n    if(open) System.out.println("Wait");\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    boolean open = false;\n    if(!open) System.out.println("Wait");\n  }\n}', 'Wait', 'fix-code', 460, 'java'),
(3, 'Ternary Operator', 'Assign "Even" or "Odd" based on x.', 'public class Main {\n  public static void main(String[] args) {\n    int x = 7;\n    String s = (x % 2 == 0) : "Even" ? "Odd";\n    System.out.println(s);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int x = 7;\n    String s = (x % 2 == 0) ? "Even" : "Odd";\n    System.out.println(s);\n  }\n}', 'Odd', 'fix-code', 510, 'java'),
(3, 'Curly Bracket Fix', 'Fix the missing bracket in if-else.', 'public class Main {\n  public static void main(String[] args) {\n    if(true)\n      System.out.println("T");\n    else\n      System.out.println("F");\n    }\n}', 'public class Main {\n  public static void main(String[] args) {\n    if(true) {\n      System.out.println("T");\n    } else {\n      System.out.println("F");\n    }\n  }\n}', 'T', 'fix-code', 425, 'java'),
(3, 'String Equality If', 'Compare two strings s1, s2 using equals(). Fix operator.', 'public class Main {\n  public static void main(String[] args) {\n    String s1 = "Hi"; String s2 = "Hi";\n    if(s1 == s2) System.out.println("Equal");\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    String s1 = "Hi"; String s2 = "Hi";\n    if(s1.equals(s2)) System.out.println("Equal");\n  }\n}', 'Equal', 'fix-code', 505, 'java'),
(3, 'Short Circuit If', 'Explain short circuiting. Fix order to prevent NPE.', 'public class Main {\n  public static void main(String[] args) {\n    String s = null;\n    if(s.length() > 0 && s != null) System.out.println("Ok");\n    else System.out.println("Null");\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    String s = null;\n    if(s != null && s.length() > 0) System.out.println("Ok");\n    else System.out.println("Null");\n  }\n}', 'Null', 'fix-code', 580, 'java'),
(3, 'Switch Basic', 'Switch on day = 1 to print "Monday". Fix syntax.', 'public class Main {\n  public static void main(String[] args) {\n    int day = 1;\n    switch(day) \n      case 1: System.out.println("Monday"); break;\n    \n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int day = 1;\n    switch(day) {\n      case 1: System.out.println("Monday"); break;\n    }\n  }\n}', 'Monday', 'fix-code', 525, 'java'),
(3, 'Switch Default', 'Add default case printing "Other". Fix missing default.', 'public class Main {\n  public static void main(String[] args) {\n    int n = 5;\n    switch(n) {\n      case 1: System.out.println("One"); break;\n    }\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int n = 5;\n    switch(n) {\n      case 1: System.out.println("One"); break;\n      default: System.out.println("Other");\n    }\n  }\n}', 'Other', 'fix-code', 545, 'java'),
(3, 'Switch Break Missing', 'What happens if break is removed? Fix to only print 1.', 'public class Main {\n  public static void main(String[] args) {\n    int n = 1;\n    switch(n) {\n      case 1: System.out.println("1");\n      case 2: System.out.println("2");\n    }\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int n = 1;\n    switch(n) {\n      case 1: System.out.println("1"); break;\n      case 2: System.out.println("2"); break;\n    }\n  }\n}', '1', 'fix-code', 565, 'java'),
(3, 'Switch String', 'Switch on color = "Red". Fix syntax.', 'public class Main {\n  public static void main(String[] args) {\n    String color = "Red";\n    switch color {\n      case "Red": System.out.println("Stop"); break;\n    }\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    String color = "Red";\n    switch(color) {\n      case "Red": System.out.println("Stop"); break;\n    }\n  }\n}', 'Stop', 'fix-code', 610, 'java'),
(3, 'Switch Expression', 'New Switch Expression (Java 14+) result. Fix syntax.', 'public class Main {\n  public static void main(String[] args) {\n    int n = 1;\n    String res = switch(n) {\n      case 1 : "One";\n      default : "More";\n    };\n    System.out.println(res);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int n = 1;\n    String res = switch(n) {\n      case 1 -> "One";\n      default -> "More";\n    };\n    System.out.println(res);\n  }\n}', 'One', 'fix-code', 690, 'java');

-- LEVEL 4: Switch & Loops
INSERT INTO questions (level_id, title, description, code_snippet, expected_answer, expected_output, type, points, language) VALUES 
(4, 'Switch Menu', 'Implement case 2 of a menu. Fix logic.', 'public class Main {\n  public static void main(String[] args) {\n    int opt = 2;\n    switch(opt) {\n      case 1: System.out.println("Add"); break;\n      case 3: System.out.println("Sub"); break;\n    }\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int opt = 2;\n    switch(opt) {\n      case 1: System.out.println("Add"); break;\n      case 2: System.out.println("Sub"); break;\n    }\n  }\n}', 'Sub', 'fix-code', 615, 'java'),
(4, 'Switch Char', 'Switch on char grade = \'B\'. Fix case label.', 'public class Main {\n  public static void main(String[] args) {\n    char grade = \'B\';\n    switch(grade) {\n      case "B": System.out.println("Good"); break;\n    }\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    char grade = \'B\';\n    switch(grade) {\n      case \'B\': System.out.println("Good"); break;\n    }\n  }\n}', 'Good', 'fix-code', 635, 'java'),
(4, 'Switch Multi-Level', 'Combine cases 1, 2, 3 as "Low". Fix missing logic.', 'public class Main {\n  public static void main(String[] args) {\n    int x = 2;\n    switch(x) {\n      case 2: System.out.println("Low"); break;\n    }\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int x = 2;\n    switch(x) {\n      case 1:\n      case 2:\n      case 3: System.out.println("Low"); break;\n    }\n  }\n}', 'Low', 'fix-code', 680, 'java'),
(4, 'Switch Rule Error', 'Fix rule based switch with block.', 'public class Main {\n  public static void main(String[] args) {\n    int n = 1;\n    switch(n) {\n      case 1 -> \n         System.out.println("Block");\n      \n    }\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int n = 1;\n    switch(n) {\n      case 1 -> {\n         System.out.println("Block");\n      }\n    }\n  }\n}', 'Block', 'fix-code', 720, 'java'),
(4, 'Yield in Switch', 'Use "yield" in switch block.', 'public class Main {\n  public static void main(String[] args) {\n    int n = 1;\n    String s = switch(n) {\n      case 1: return "Y";\n      default: return "N";\n    };\n    System.out.println(s);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int n = 1;\n    String s = switch(n) {\n      case 1: yield "Y";\n      default: yield "N";\n    };\n    System.out.println(s);\n  }\n}', 'Y', 'fix-code', 750, 'java'),
(4, 'Switch Constant Only', 'Can switch use variables in cases? Fix it.', 'public class Main {\n  public static void main(String[] args) {\n    int target = 5;\n    int x = 5;\n    switch(x) {\n      case target: System.out.println("Hit"); break;\n    }\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int target = 5;\n    int x = 5;\n    switch(x) {\n      case 5: System.out.println("Hit"); break;\n    }\n  }\n}', 'Hit', 'fix-code', 785, 'java'),
(4, 'Switch Enum', 'Basic idea of switch on enum.', 'public class Main {\n  enum Status { ON, OFF }\n  public static void main(String[] args) {\n    Status s = Status.ON;\n    switch(s) {\n      case "ON": System.out.println("Running"); break;\n    }\n  }\n}', 'public class Main {\n  enum Status { ON, OFF }\n  public static void main(String[] args) {\n    Status s = Status.ON;\n    switch(s) {\n      case ON: System.out.println("Running"); break;\n    }\n  }\n}', 'Running', 'fix-code', 820, 'java'),
(4, 'Switch Null Pointer', 'Protect switch from NPE with try-catch.', 'public class Main {\n  public static void main(String[] args) {\n    String s = null; \n    switch(s) { case "a": break; }\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    try {\n      String s = null; switch(s) { case "a": break; }\n    } catch(NullPointerException e) {\n      System.out.println("NPE");\n    }\n  }\n}', 'NPE', 'fix-code', 850, 'java'),
(4, 'Switch Range Illusion', 'Switch cannot do x > 10. Fix to use IF.', 'public class Main {\n  public static void main(String[] args) {\n    int x = 11;\n    switch(x) {\n      case (x > 10): System.out.println(">10"); break;\n    }\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int x = 11;\n    if(x > 10) System.out.println(">10");\n  }\n}', '>10', 'fix-code', 705, 'java'),
(4, 'Switch Case Order', 'Fix default case to be at the end.', 'public class Main {\n  public static void main(String[] args) {\n    int x = 2;\n    switch(x) {\n      case 2: System.out.println("2");\n      default: System.out.println("D"); break;\n    }\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int x = 2;\n    switch(x) {\n      case 2: System.out.println("2"); break;\n      default: System.out.println("D");\n    }\n  }\n}', '2', 'fix-code', 760, 'java'),
(4, 'While Loop Basic', 'Print 1-3 using while. Fix loop infinity.', 'public class Main {\n  public static void main(String[] args) {\n    int i = 1;\n    while(i <= 3) {\n       System.out.println(i);\n    }\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int i = 1;\n    while(i <= 3) {\n       System.out.println(i++);\n    }\n  }\n}', '1\n2\n3', 'fix-code', 810, 'java'),
(4, 'For Loop Basics', 'Print 0-2. Fix loop condition.', 'public class Main {\n  public static void main(String[] args) {\n    for(int i=0; i<=3; i++) System.out.println(i);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    for(int i=0; i<3; i++) System.out.println(i);\n  }\n}', '0\n1\n2', 'fix-code', 840, 'java'),
(4, 'Do-While Once', 'Execution at least once. Fix condition to stop after one run.', 'public class Main {\n  public static void main(String[] args) {\n    int x = 10;\n    do {\n      System.out.println("Run");\n    } while(x == 10);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int x = 10;\n    do {\n      System.out.println("Run");\n    } while(x < 5);\n  }\n}', 'Run', 'fix-code', 865, 'java'),
(4, 'Infinite Loop Break', 'Break out of infinite loop.', 'public class Main {\n  public static void main(String[] args) {\n    while(true) {\n       System.out.println("Bye");\n       // Missing break\n    }\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    while(true) {\n       System.out.println("Bye");\n       break;\n    }\n  }\n}', 'Bye', 'fix-code', 890, 'java'),
(4, 'For-Each Loop', 'Iterate simple array. Fix syntax.', 'public class Main {\n  public static void main(String[] args) {\n    int[] nums = {1, 2};\n    for(int i=0; i<nums.length; i) System.out.println(nums[i]);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int[] nums = {1, 2};\n    for(int n : nums) System.out.println(n);\n  }\n}', '1\n2', 'fix-code', 915, 'java');

-- LEVEL 5: Loops & Arrays
INSERT INTO questions (level_id, title, description, code_snippet, expected_answer, expected_output, type, points, language) VALUES 
(5, 'Loop Sum', 'Sum numbers 1 to 5.', 'public class Main {\n  public static void main(String[] args) {\n    int sum = 0;\n    for(int i=1; i<5; i++) sum += i;\n    System.out.println(sum);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int sum = 0;\n    for(int i=1; i<=5; i++) sum += i;\n    System.out.println(sum);\n  }\n}', '15', 'fix-code', 945, 'java'),
(5, 'Nested For', 'Print 2x2 grid of *.', 'public class Main {\n  public static void main(String[] args) {\n    for(int i=0; i<2; i++) {\n      for(int j=0; j<2; j++) System.out.print("*");\n    }\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    for(int i=0; i<2; i++) {\n      for(int j=0; j<2; j++) System.out.print("*");\n      System.out.println();\n    }\n  }\n}', '**\n**', 'fix-code', 980, 'java'),
(5, 'Continue Statement', 'Skip number 2 in 1-3.', 'public class Main {\n  public static void main(String[] args) {\n    for(int i=1; i<=3; i++) {\n      System.out.println(i);\n    }\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    for(int i=1; i<=3; i++) {\n      if(i == 2) continue;\n      System.out.println(i);\n    }\n  }\n}', '1\n3', 'fix-code', 1050, 'java'),
(5, 'Reverse Loop', 'Loop 3 down to 1.', 'public class Main {\n  public static void main(String[] args) {\n    for(int i=1; i<=3; i++) System.out.println(i);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    for(int i=3; i>=1; i--) System.out.println(i);\n  }\n}', '3\n2\n1', 'fix-code', 910, 'java'),
(5, 'While Factorial', 'Factorial of 3.', 'public class Main {\n  public static void main(String[] args) {\n    int f = 0; int i = 1;\n    while(i <= 3) f *= i++;\n    System.out.println(f);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int f = 1; int i = 1;\n    while(i <= 3) f *= i++;\n    System.out.println(f);\n  }\n}', '6', 'fix-code', 1100, 'java'),
(5, 'Array Declare', 'Declare int array size 5.', 'public class Main {\n  public static void main(String[] args) {\n    int[] arr = new int[0];\n    System.out.println(arr.length);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int[] arr = new int[5];\n    System.out.println(arr.length);\n  }\n}', '5', 'fix-code', 1150, 'java'),
(5, 'Array Inline', 'Initialize array with 1, 3, 5.', 'public class Main {\n  public static void main(String[] args) {\n    int[] arr = {};\n    System.out.println(arr[1]);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int[] arr = {1, 3, 5};\n    System.out.println(arr[1]);\n  }\n}', '3', 'fix-code', 1200, 'java'),
(5, 'Index Out Of Bound', 'Fix the loop index error.', 'public class Main {\n  public static void main(String[] args) {\n    int[] arr = {1, 2};\n    for(int i=0; i<=arr.length; i++) System.out.println(arr[i]);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int[] arr = {1, 2};\n    for(int i=0; i<arr.length; i++) System.out.println(arr[i]);\n  }\n}', '1\n2', 'fix-code', 1250, 'java'),
(5, 'Array Sum', 'Sum of {10, 20}.', 'public class Main {\n  public static void main(String[] args) {\n    int[] a = {10, 20};\n    System.out.println(a[0]);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int[] a = {10, 20};\n    System.out.println(a[0] + a[1]);\n  }\n}', '30', 'fix-code', 1300, 'java'),
(5, '2D Array', 'Access [0][1] of {{1,2},{3,4}}.', 'public class Main {\n  public static void main(String[] args) {\n    int[][] m = {{1, 2}, {3, 4}};\n    System.out.println(m[1][1]);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int[][] m = {{1, 2}, {3, 4}};\n    System.out.println(m[0][1]);\n  }\n}', '2', 'fix-code', 1400, 'java'),
(5, 'Array Copy', 'Use System.arraycopy concept.', 'public class Main {\n  public static void main(String[] args) {\n    int[] a = {1}; int[] b = new int[1];\n    // Copy code missing\n    System.out.println(b[0]);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int[] a = {1}; int[] b = new int[1];\n    System.arraycopy(a, 0, b, 0, 1);\n    System.out.println(b[0]);\n  }\n}', '1', 'fix-code', 1450, 'java'),
(5, 'Sort Array', 'Use Arrays.sort() on {3, 1, 2}.', 'import java.util.Arrays;\npublic class Main {\n  public static void main(String[] args) {\n    int[] a = {3, 1, 2};\n    // Sort a\n    System.out.println(a[0]);\n  }\n}', 'import java.util.Arrays;\npublic class Main {\n  public static void main(String[] args) {\n    int[] a = {3, 1, 2};\n    Arrays.sort(a);\n    System.out.println(a[0]);\n  }\n}', '1', 'fix-code', 1500, 'java'),
(5, 'String Array', 'Array of names.', 'public class Main {\n  public static void main(String[] args) {\n    String[] ns = new String[0];\n    System.out.println(ns.length);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    String[] ns = {"A", "B"};\n    System.out.println(ns.length);\n  }\n}', '2', 'fix-code', 1100, 'java'),
(5, 'Array Search', 'Find index of 5 in {1, 5, 2}.', 'public class Main {\n  public static void main(String[] args) {\n    int[] a = {1, 5, 2};\n    for(int i=0; i<a.length; i++) if(a[i]==7) System.out.println(i);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int[] a = {1, 5, 2};\n    for(int i=0; i<a.length; i++) if(a[i]==5) System.out.println(i);\n  }\n}', '1', 'fix-code', 1550, 'java'),
(5, 'Multidimensional Row Length', 'Length of first row in {{1,2,3},{4}}.', 'public class Main {\n  public static void main(String[] args) {\n    int[][] m = {{1,2,3},{4}};\n    System.out.println(m.length);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int[][] m = {{1,2,3},{4}};\n    System.out.println(m[0].length);\n  }\n}', '3', 'fix-code', 1600, 'java'),
(5, 'Capstone: Binary Search mid', 'Fix the potential overflow in mid calculation.', 'public class Main {\n  public static void main(String[] args) {\n    int low = 10, high = 20;\n    int mid = (low + high) / 2;\n    System.out.println(mid);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int low = 10, high = 20;\n    int mid = low + (high - low) / 2;\n    System.out.println(mid);\n  }\n}', '15', 'fix-code', 2000, 'java');

-- LEVEL 6: Cyber Warrior (Advanced logic & strings)
INSERT INTO questions (level_id, title, description, code_snippet, expected_answer, expected_output, type, points, language) VALUES 
(6, 'StringBuilder Append', 'Append "Code" and "Point" using StringBuilder.', 'public class Main {\n  public static void main(String[] args) {\n    StringBuilder sb = new StringBuilder();\n    sb.add("Code");\n    System.out.println(sb.toString());\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    StringBuilder sb = new StringBuilder();\n    sb.append("Code");\n    sb.append("Point");\n    System.out.println(sb.toString());\n  }\n}', 'CodePoint', 'fix-code', 2200, 'java'),
(6, 'Bitwise AND', 'Calculate 12 AND 7.', 'public class Main {\n  public static void main(String[] args) {\n    System.out.println(12 & 7);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    System.out.println(12 & 7);\n  }\n}', '4', 'fix-code', 2100, 'java'),
(6, 'Prime Check Logic', 'Check if 17 is prime. Fix the loop condition.', 'public class Main {\n  public static void main(String[] args) {\n    int n = 17; boolean p = true;\n    for(int i=2; i<n/2; i++) if(n%i==0) p=false;\n    System.out.println(p);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int n = 17; boolean p = true;\n    for(int i=2; i*i<=n; i++) if(n%i==0) p=false;\n    System.out.println(p);\n  }\n}', 'true', 'fix-code', 2500, 'java');

-- LEVEL 7: System Architect (OOP Foundations)
INSERT INTO questions (level_id, title, description, code_snippet, expected_answer, expected_output, type, points, language) VALUES 
(7, 'Method Static Access', 'Fix the static method call.', 'public class Main {\n  void sayHi() { System.out.println("Hi"); }\n  public static void main(String[] args) {\n    sayHi();\n  }\n}', 'public class Main {\n  static void sayHi() { System.out.println("Hi"); }\n  public static void main(String[] args) {\n    sayHi();\n  }\n}', 'Hi', 'fix-code', 3000, 'java'),
(7, 'Private Field Access', 'Use a getter to access private field.', 'class User {\n  private String name = "Admin";\n}\npublic class Main {\n  public static void main(String[] args) {\n    User u = new User();\n    System.out.println(u.name);\n  }\n}', 'class User {\n  private String name = "Admin";\n  public String getName() { return name; }\n}\npublic class Main {\n  public static void main(String[] args) {\n    User u = new User();\n    System.out.println(u.getName());\n  }\n}', 'Admin', 'fix-code', 3500, 'java'),
(7, 'Constructor Super', 'Call parent constructor.', 'class Parent { Parent(String s) { System.out.println(s); } }\nclass Child extends Parent {\n  Child() { System.out.println("C"); }\n}\npublic class Main { public static void main(String[] args) { new Child(); } }', 'class Parent { Parent(String s) { System.out.println(s); } }\nclass Child extends Parent {\n  Child() { super("P"); System.out.println("C"); }\n}\npublic class Main { public static void main(String[] args) { new Child(); } }', 'P\nC', 'fix-code', 4000, 'java');

-- LEVEL 8: Coding Deity (Algorithms & Advanced Logic)
INSERT INTO questions (level_id, title, description, code_snippet, expected_answer, expected_output, type, points, language) VALUES 
(8, 'Recursive Factorial', 'Fix the recursive base case.', 'public class Main {\n  static int fact(int n) {\n    return n * fact(n-1);\n  }\n  public static void main(String[] args) {\n    System.out.println(fact(3));\n  }\n}', 'public class Main {\n  static int fact(int n) {\n    if(n <= 1) return 1;\n    return n * fact(n-1);\n  }\n  public static void main(String[] args) {\n    System.out.println(fact(3));\n  }\n}', '6', 'fix-code', 5000, 'java'),
(8, 'Array Minimum', 'Find minimum value.', 'public class Main {\n  public static void main(String[] args) {\n    int[] a = {10, 5, 20};\n    int m = a[0];\n    for(int x : a) if(x > m) m = x;\n    System.out.println(m);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int[] a = {10, 5, 20};\n    int m = a[0];\n    for(int x : a) if(x < m) m = x;\n    System.out.println(m);\n  }\n}', '5', 'fix-code', 5500, 'java'),
(8, 'Sum of Even numbers', 'Sum only even values in {1, 2, 3, 4}.', 'public class Main {\n  public static void main(String[] args) {\n    int[] a = {1, 2, 3, 4};\n    int s = 0;\n    for(int x : a) s += x;\n    System.out.println(s);\n  }\n}', 'public class Main {\n  public static void main(String[] args) {\n    int[] a = {1, 2, 3, 4};\n    int s = 0;\n    for(int x : a) if(x % 2 == 0) s += x;\n    System.out.println(s);\n  }\n}', '6', 'fix-code', 6000, 'java');
